modelDir: "/usr/src/app/swagger_server/pose/posenet/served_model"
databaseDir: "../db/"
poseFolder: "/tmp/physio/poses"
staticFileDir: "/usr/src/app/static/"
electrodesFolder: "/tmp/physio/placements"